version: '3.9'

services:
  moedinhas:
    build: .
    ports:
      - "5123:5123"
    volumes:
      - .:/app
      - moedinhas_db:/app/moedinhas.db
    env_file:
      - .env

volumes:
  moedinhas_db:
