name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to Lightsail via SSH
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
        username: deploy-user
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: "."
        target: "/opt/HOME/moedinhas"

    - name: Remote SSH commands
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
        username: deploy-user
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /opt/HOME/moedinhas
          echo "FLASK_ENV=production" > .env
          echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> .env
          echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> .env
          echo "VAPID_CLAIMS_SUB=${{ secrets.VAPID_CLAIMS_SUB }}" >> .env
          docker-compose down
          docker-compose up -d --build